name: shoot

channels:
  - conda-forge

dependencies:
  - argopy>=1.4
  - cartopy
  - cmocean
  - colorlog
  - contourpy
  - gsw
  - matplotlib
  - netCDF4
  - psutil
  - owslib
  - scipy
  - xarray
  - xoa
